Nikhil2
oss-slu/lrda_mobile pull request #189
Opened 2024-10-14 19:09 UTC by teamomiamigo

Fixes #185: implement Image Insertion Functionality in Text Editor with Block-Level Display

This PR introduces functionality that allows users to insert images into their notes on the Add Notes screen. The inserted images are displayed as block-level elements, ensuring that they appear full-width and text begins on a new line after the image. This enhances the overall user experience by providing more flexibility in how users can structure their notes.

**Why was it changed**
Previously, users could not insert images in a proper block-level format, and there were issues with image sizing and placement. With this change, users can insert images that are 100px by 100px in size, improving note organization and making the note editor more user-friendly.

**How was it changed**
- The `addImageToEditor` function was modified to insert an image as a block-level element with a fixed size of 100px by 100px.
- The image is automatically inserted on a new line, and any text following the image begins on a new line as well.
- Additional styling was added to ensure the image fits within the note’s container, providing a clean layout for images in notes.
- Test cases were add to ensure that the images that are added are in the certain specifications

**UI after changes**
After the changes, the user can click the image icon in the toolbar, select an image, and have it inserted into the note as a block-level element, sized to 100px by 100px, and any text after the image starts on a new line. The image is fully visible, enhancing the user experience in note-taking.

![sprint3](https://github.com/user-attachments/assets/cf18e0d4-39f9-4d95-ad15-0c94aa28edc0)

2024-10-14 22:31 UTC, AmarHadzic reviewed
Overall, good implementation! I think I saw some stuff apart of other stories, other than that, it looks good.

2024-10-14 22:31 UTC, AmarHadzic commented on lib/screens/AddNoteScreen.tsx
> +    const imgTag = `<img src="${imageUri}" style="width: 100px; height: 100px; display: block; margin: 10px 0;" />&nbsp;<br><br>`;
nice clean solution, simple way of making images attachable to the text editor

2024-10-14 22:31 UTC, AmarHadzic commented on lib/screens/mapPage/ExploreScreen.js
> +      const fetchedNotes = await ApiService.fetchMessages(globeIcon === "earth", globeIcon !== "earth", "someUserId");
Is this for another story?

2024-10-14 22:31 UTC, AmarHadzic commented on lib/screens/mapPage/ExploreScreen.js
> +        if (latitude === 0 || longitude === 0 || latitude < -90 || latitude > 90 || longitude < -180 || longitude > 180) {
It looks like this was apart of the map pins story?

2024-10-14 22:31 UTC, AmarHadzic commented on __tests__/AddNoteScreen.test.tsx
> +import { fireEvent, render, waitFor } from '@testing-library/react-native';
nice job adding tests

2024-10-15 19:05 UTC, kate-holdener commented
> Hi, something messed up with my commit and the PR request when it comes to committing my recent changes, so please look at my most recent commit for the changes that I made in regards to this. I apologize for this, as my previous PR wasn't closed and I didn't know and I accidentally committed it to the previous PR request.

@teamomiamigo You should be starting each new issue by creating a branch off the main branch. You are creating branches from your other unmerged branches, which is causing these problems. Please follow the standard process and start each sprint with a new branch off main.

2024-10-16 22:15 UTC, rcAsironman commented
@teamomiamigo , I've come across a few issues in your code and would like to point them out below.

issue 1:

You are working on the old version of the code. The new version of the code is available on the main branch. Before you start working on a new issue, it is best practice to pull the latest version of the code from the main branch.

Note: In the old version of the code, we were using **'react-native-pell-rich-editor,'** but in the latest version, we are working with the **10Tap editor**.

issue 2:

Even though you are working on the old version of the code, a few test cases are failing.

<img width="400" alt="Screenshot 2024-10-16 at 5 09 57 PM" src="https://github.com/user-attachments/assets/1e6781c0-3b84-48db-92da-f16b50bc376f">

2024-10-23 15:16 UTC, rcAsironman requested changes
@teamomiamigo You are working on an old version of the main branch. To resolve this, pull the latest changes from the main branch and start working on it.

2025-08-14 21:14 UTC, closed without merging