187 Ten Tap
oss-slu/lrda_mobile pull request #190
Opened 2024-10-14 22:26 UTC by ademDurakovic

Fixes #187 

Fixes: Replaced the richTextEditor to use the new tenTap library.

Why: TenTap is a more active library with help.

What got changed: Library import was added the editor was initialized and JSX components were added like the textpad/

2024-10-15 02:57 UTC, teamomiamigo reviewed
Overall, great addition to the file and in changing the text editor. Has made the code a little more simpler and cleaner.

2024-10-15 02:57 UTC, teamomiamigo commented on lib/screens/EditNoteScreen.tsx
> +
i see the addition for importing these tools

2024-10-15 02:57 UTC, teamomiamigo commented on lib/screens/EditNoteScreen.tsx
> +        </View>
Nice addition to the code and watching out for anything that needed to be added.

2024-10-15 23:55 UTC, rcAsironman commented
@ademDurakovic, you did a good job, but a few things should be improved in your work.

The Toolbar Alignment Issue: The toolbar is not aligned properly; it should be positioned right above the keyboard.

Your Output on Android:
<img width="400" alt="Toolbar_current_output" src="https://github.com/user-attachments/assets/ec9e313d-a1c7-49ca-a61b-8f01787c48f8">

Your Output on iOS:
<img width="400" alt="Toolbar_current_output" src="https://github.com/user-attachments/assets/ba57486d-e068-4dba-bd5e-297fbda30e4a">


Expected Output:
<img width="400" alt="Mobile_editing" src="https://github.com/user-attachments/assets/6105a107-6b0d-45dd-a88a-45ea544c4176">


Theme Issue:
In dark mode, the editor should have a black background with white text. The opposite should apply for light mode.
Your Output on Android:

<img width="400" alt="TextEditor_In_dark_mode" src="https://github.com/user-attachments/assets/a36fbf84-41b9-4f62-89dc-f3d6a2ed41c1">


Your Output on iOS:

<img width="400" alt="TextEditor_In_dark_mode" src="https://github.com/user-attachments/assets/4dff9ee6-fe02-4986-b619-dc2ec488fcbe">

2024-10-20 19:09 UTC, ademDurakovic commented
> @ademDurakovic, you did a good job, but a few things should be improved in your work.
> 
> The Toolbar Alignment Issue: The toolbar is not aligned properly; it should be positioned right above the keyboard.
> 
> Your Output on Android: <img alt="Toolbar_current_output" width="400" src="https://private-user-images.githubusercontent.com/165144522/376828036-ec9e313d-a1c7-49ca-a61b-8f01787c48f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDM5NjAsIm5iZiI6MTcyOTQ0MzY2MCwicGF0aCI6Ii8xNjUxNDQ1MjIvMzc2ODI4MDM2LWVjOWUzMTNkLWExYzctNDljYS1hNjFiLThmMDE3ODdjNDhmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNzAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGFlMmNhYTYwODU2OTc0OWMxYmJjOWEwYjkxZjE2ZTkzYjZiOGM3ZDdjYmMzZjYxOGQ0M2I0NGU4MDlkNjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WutvdAz_1slvT6GLMOdpJl4s-EOFwfMR1j5GhZVAq6A">
> 
> Your Output on iOS: <img alt="Toolbar_current_output" width="400" src="https://private-user-images.githubusercontent.com/165144522/376835339-ba57486d-e068-4dba-bd5e-297fbda30e4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDM5NjAsIm5iZiI6MTcyOTQ0MzY2MCwicGF0aCI6Ii8xNjUxNDQ1MjIvMzc2ODM1MzM5LWJhNTc0ODZkLWUwNjgtNGRiYS1iZDVlLTI5N2ZiZGEzMGU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNzAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDNlNmU4YmJhNTQzZjNkZTIyNDA3OGE0ZDBlNzMxMjRlMjAzNWFkOTU4ZWRhOTg5OTcwNWUzNmUwZmI2MTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w9iUWDNHnweGymGnw4682y_F-sjA4hKyNj5t7DniN6U">
> 
> Expected Output: <img alt="Mobile_editing" width="400" src="https://private-user-images.githubusercontent.com/165144522/376828534-6105a107-6b0d-45dd-a88a-45ea544c4176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDM5NjAsIm5iZiI6MTcyOTQ0MzY2MCwicGF0aCI6Ii8xNjUxNDQ1MjIvMzc2ODI4NTM0LTYxMDVhMTA3LTZiMGQtNDVkZC1hODhhLTQ1ZWE1NDRjNDE3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNzAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjBiZDczMzhiOTU1NTdiNWEzMjAwYjE4ZTE2NTc5NDgyYTk0NTUxZDYxNGE2OGE2NzAyZTI5NTE5NmEyYzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YhW4Wf3Rlp1qMtS8pg0J0WiMZKU7t5Y-1gAzX768Xpk">
> 
> Theme Issue: In dark mode, the editor should have a black background with white text. The opposite should apply for light mode. Your Output on Android:
> 
> <img alt="TextEditor_In_dark_mode" width="400" src="https://private-user-images.githubusercontent.com/165144522/376833048-a36fbf84-41b9-4f62-89dc-f3d6a2ed41c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDM5NjAsIm5iZiI6MTcyOTQ0MzY2MCwicGF0aCI6Ii8xNjUxNDQ1MjIvMzc2ODMzMDQ4LWEzNmZiZjg0LTQxYjktNGY2Mi04OWRjLWYzZDZhMmVkNDFjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNzAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDEzNTdiZTk3N2I4ZWMzOTI5M2Q0OGM0ZDBjYTViZjMzMjVhNWVkYjVjNTMxNDA5OGM4MGI4MjMyZWQyMmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-rYWBfA2WvCFZWGVS_R1ps2vJkYY_4JBGoRzxw25jg4">
> Your Output on iOS:
> 
> <img alt="TextEditor_In_dark_mode" width="400" src="https://private-user-images.githubusercontent.com/165144522/376834249-4dff9ee6-fe02-4986-b619-dc2ec488fcbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDM5NjAsIm5iZiI6MTcyOTQ0MzY2MCwicGF0aCI6Ii8xNjUxNDQ1MjIvMzc2ODM0MjQ5LTRkZmY5ZWU2LWZlMDItNDk4Ni1iNjE5LWRjMmVjNDg4ZmNiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNzAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjI0NWYwZGE2MzcyYjlhZWRhZmI1YWQzMDllZTcxZTgzMDFmYzViZTNlNzljZWM3ZjE3NjI0YzBjMDgxMWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S5RzuV3gDNxqDNoslC6NepLP2J9UjZ6HJlKZ5Ond6OY">



> 

Here are how the new changes look:
Text is dynamically updated based on theme, and adjusted the toolbar.

![image](https://github.com/user-attachments/assets/3d89dc8c-f3f0-41bc-a90c-846143457df3)
<img width="313" alt="image" src="https://github.com/user-attachments/assets/8e23efeb-165c-4354-942a-f9ced6e63912">
<img width="296" alt="image" src="https://github.com/user-attachments/assets/15e2337d-0095-491a-ae8f-26ea6156263d">

2024-10-23 15:11 UTC, rcAsironman requested changes
@AdemDurakovic On Android, dark mode is not working as expected. The editor remains white while in dark mode. Please modify the code to set it to black.

2024-10-28 22:33 UTC, teamomiamigo reviewed
Overall, great work on this, everything looks great and all the additions seem valid and correct! Great job!

2024-10-28 22:33 UTC, teamomiamigo commented on lib/screens/EditNoteScreen.tsx
> +
good rework to make sure instantiating an editor

2024-10-28 22:33 UTC, teamomiamigo commented on lib/screens/EditNoteScreen.tsx
> +      }),
good add, specifically for andriod to make sure that the colors are correct

2024-10-28 22:33 UTC, teamomiamigo commented on lib/screens/EditNoteScreen.tsx
> +      }),
proper for android coloring again, looks nice.

2024-10-28 22:33 UTC, teamomiamigo commented on lib/screens/EditNoteScreen.tsx
> +            style={[exampleStyles.editor, {backgroundColor: Platform.OS == "android" && theme.tertiaryColor}]} // Apply styling here
nice, making sure it follows the theme

2024-10-28 22:33 UTC, teamomiamigo commented on lib/screens/EditNoteScreen.tsx
> +
making sure the visibility is true, good job!

2024-10-28 23:40 UTC, rcAsironman commented on lib/screens/EditNoteScreen.tsx
> +      console.log("text color will be: " , theme.text);
please remove the log statements.

2024-10-28 23:42 UTC, rcAsironman commented on lib/screens/EditNoteScreen.tsx
> +    console.log("text color will be: #F7F8F9 from IF state");
Remove any log statements before committing.

2024-10-28 23:53 UTC, rcAsironman requested changes
@ademDurakovic I like the changes you've made. But, I came across an issue: the toolbar is not aligned properly.

Issue:

On iOS 12, the toolbar is not showing. It should work on all devices.
![IMG_0223](https://github.com/user-attachments/assets/ec97c2dc-958c-4136-a695-01c89bc63913)

2024-10-30 19:09 UTC, yashb196 requested changes
Overall Good Effort however when you enter EditNoteScreen you see this error on the console log 

**### Warning: React has detected a change in the order of Hooks called by EditNoteScreen. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useState                   useState
3. useState                   useState
4. useState                   useState
5. useState                   useState
6. useState                   useState
7. useState                   useState
8. useState                   useState
9. useState                   useState
10. useRef                    useRef
11. useState                  useState
12. useState                  useState
13. useState                  useState
14. useState                  useState
15. useState                  useState
16. useState                  useState
17. useState                  useState
18. useState                  useState
19. useRef                    useRef
20. useState                  useState
21. useState                  useState
22. useState                  useState
23. useContext                useContext
24. useState                  useState
25. useRef                    useRef
26. useRef                    useRef
27. useRef                    useRef
28. useRef                    useRef
29. useMemo                   useMemo
30. useMemo                   useMemo
31. useEffect                 useEffect
32. useEffect                 useEffect
33. useState                  useState
34. useState                  useState
35. useEffect                 useEffect
36. useEffect                 useEffect
37. useEffect                 useEffect
38. useState                  useState
39. useState                  useState
40. useRef                    useRef
41. useState                  useState
42. useEffect                 useEffect
43. useContext                useContext
44. useContext                useContext
45. useContext                useContext
46. useContext                useContext
47. useContext                useContext
48. useContext                useContext
49. useContext                useContext
50. useContext                useContext
51. useContext                useContext
52. useContext                useContext
53. useContext                useContext
54. useContext                useContext
55. undefined                 useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in EditNoteScreen (created by EditNote)
    in EditNote (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View (created by Animated(View))
    in Animated(View) (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View (created by Animated(View))
    in Animated(View) (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RCTView (created by View)
    in View (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by StackView)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by HomeStack)
    in HomeStack (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RCTView (created by View)
    in View (created by ResourceSavingScene)
    in RCTView (created by View)
    in View (created by ResourceSavingScene)
    in ResourceSavingScene (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RCTView (created by View)
    in View (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by AppNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by AppNavigator)
    in AppNavigator (created by App)
    in ThemeProvider (created by App)
    in Provider (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)**
    
    this will break the application I would ask you to have a look at this and fix it before merging

2024-11-04 01:31 UTC, rcAsironman requested changes
@ademDurakovic On Android, two toolbars are being rendered. Please check iOS as well.

<img width="200" src="https://github.com/user-attachments/assets/a0e11e51-5f43-4aaa-8fd5-30680252b4d5"></img>

2024-11-04 23:30 UTC, rcAsironman approved these changes

2024-11-05 00:49 UTC, yashb196 approved these changes

2024-11-05 00:49 UTC, merged