Update The Theme Text Dynamically (issue #193)
oss-slu/lrda_mobile pull request #195
Opened 2024-10-28 18:39 UTC by teamomiamigo

**Fixes #193:** Update Theme Text to Reflect Dark/Light Mode Changes in MorePage
This PR updates the theme text in MorePage.tsx to reflect the current mode, whether dark or light. The text now clearly indicates "Dark Mode" or "Light Mode" and displays in the appropriate color, enhancing user clarity when switching between themes.

**Why Was It Changed?**
Previously, when switching between dark mode and light mode, the text indicating the current theme did not update accordingly. By ensuring that the theme text changes dynamically, users can easily identify the current mode they are in, improving the overall user experience.

**How Was It Changed?**
The theme switch functionality in MorePage.tsx was updated to modify the text based on the selected theme:
"Dark Mode" is displayed in white text when dark mode is active.
"Light Mode" is displayed in black text when light mode is active.
Additional test cases were created to validate the text changes when switching between themes. 

**UI After Changes**
After the changes, when the user toggles between dark mode and light mode, the theme text updates dynamically. When in dark mode, it clearly displays "Dark Mode" in white, and when in light mode, it displays "Light Mode" in black.
![Screenshot 2024-10-28 at 12.13.38 PM.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/160623b4-ee42-4de8-826f-7fb3b3374ed7/ee96584d-8c3c-4a57-b178-d355596151be/Screenshot_2024-10-28_at_12.13.38_PM.png)
![Screenshot 2024-10-28 at 12.13.48 PM.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/160623b4-ee42-4de8-826f-7fb3b3374ed7/f5b8fd22-41d2-4be9-aa48-0c8a23656c43/Screenshot_2024-10-28_at_12.13.48_PM.png)

2024-10-28 22:32 UTC, AmarHadzic reviewed
Overall, good job!

2024-10-28 22:32 UTC, AmarHadzic commented on lib/screens/MorePage.tsx
> +                <Text style={[styles.switchText, isDarkmode ? styles.darkModeText : styles.lightModeText]}>{isDarkmode ? "Dark Mode" : "Light Mode"}</Text>
I would suggest adding some comments on your code.

2024-10-28 22:32 UTC, AmarHadzic commented on lib/screens/MorePage.tsx
> +  lightModeText: {
Nice and simple code here. Very understandable without the need to use comments.

2024-10-28 22:32 UTC, AmarHadzic commented on __tests__/MoreScreen.test.tsx
> +
Good test cases and good comments. However some comments can be better, like comment on what it is testing and what the value should be.

2024-10-29 00:21 UTC, rcAsironman requested changes
@teamomiamigo The code is working as expected, but please use the theme object to apply the themes instead of creating separate CSS properties on line 148.

2024-10-31 16:22 UTC, teamomiamigo commented
attached are the changes made on line 148 of MorePage that uses the theme object to ensure the color of the text.

2024-11-01 15:27 UTC, rcAsironman requested changes
@teamomiamigo All checks have failed. Please review your work before submitting, and run it on your local machine first.

2024-11-05 00:58 UTC, rcAsironman approved these changes

2024-11-07 21:59 UTC, rcAsironman approved these changes

2024-11-09 03:08 UTC, merged