Tutorial Onboarding
oss-slu/lrda_mobile pull request #200
Opened 2024-11-11 15:32 UTC by ademDurakovic

Fixes #198 

**What Got Changed**
New widgets were added to help guide a new user throughout the app. 

** Why it got changed? ** 
This provides a smoother onboarding for our new user's and could clear up some confusion on how to use the app. 

** How it was changed **

IN PROGRESS!
Widgets are displayed with some JSX from a library.

Widgets from a tooltip library have been added but show up on every user log on. Currently the userData type needs to be updated and a new PUT API called Edit_User should be created to help keep track if the user has completed the onboarding, if they have then these widgets won't show.

2024-11-11 23:14 UTC, AmarHadzic commented on lib/screens/HomeScreen.tsx
> +
add some comments on your code

2024-11-11 23:25 UTC, teamomiamigo reviewed
overall, looks great! The additions are fine, just check if everything works out properly, and cleaning up the code a little bit by removing all the white spaces and also adding more comments into certain sections of the code to define its function.

2024-11-11 23:25 UTC, teamomiamigo commented on lib/screens/HomeScreen.tsx
> +    },
Good job on the styles, they look proper and keep it concise, along with adding comments to describe what the styling is doing.

2024-11-11 23:25 UTC, teamomiamigo commented on lib/screens/HomeScreen.tsx
> +              handleFilters(newValue);
items for creating the tutorial looks proper with the everything labeled. add more comments to give better understanding of the functioning specifically

2024-11-11 23:25 UTC, teamomiamigo commented on lib/screens/mapPage/ExploreScreen.js
> +            >
add comments to this code to describe and show what you are doing here.

2024-11-11 23:25 UTC, teamomiamigo commented on yarn.lock
> +prop-types@^15.5.7, prop-types@^15.6.1, prop-types@^15.6.2, prop-types@^15.7.2, prop-types@^15.8.1:
why are you changing the version down? maybe add a code to show why this is happening

2024-11-12 15:29 UTC, rcAsironman commented on lib/screens/HomeScreen.tsx
> +
remove console statement.

2024-11-12 15:44 UTC, rcAsironman requested changes
@ademDurakovic Your work is impressive, I just have a few suggestions to make the app even better:

Adding a "Skip Tutorial" button would be helpful for users who don’t want to go through the tutorial. Some users may already know how to use the app.

Including the user account/profile page in the tutorial would make it easier for users to understand and access.

It would also be great to show the dark mode feature in the tutorial for users who prefer it.

Lastly, please create test cases for these changes to make sure everything works smoothly.

2024-11-26 17:03 UTC, rcAsironman requested changes
Hi @ademDurakovic, could you please upgrade your branch to the latest SDK version (SDK 52)? I'm currently unable to run your project.

Error:
![IMG_0356](https://github.com/user-attachments/assets/87564976-d008-42b0-8d04-76fb8e2b7573)

2024-12-02 20:16 UTC, rcAsironman requested changes
@ademDurakovic Some test cases are failing. Please make sure all the test cases pass.

<img width="470" alt="Screenshot 2024-12-02 at 2 14 29 PM" src="https://github.com/user-attachments/assets/435c78c5-3efb-4dd6-86d6-4376e64c249b">

2025-04-17 16:58 UTC, closed without merging